{% set name = "pangolin" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: a680d1b52cd432f93f3359cb8f2179b25acf384d29dbaa2530b2eb3dfe5a81c6
  url: https://github.com/christian-rauch/Pangolin/archive/refs/tags/x.1.tar.gz
  sha256: a01d2ba1111b1c31125affd528e81eca97a22365790890feda152bb98d70c4d2

build:
  script: |
    cmake -G Ninja -B build -D CMAKE_INSTALL_PREFIX:PATH=$PREFIX
    cmake --build build --target install

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - eigen
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libegl-devel') }}
    - glew
    - libpng
    - libjpeg-turbo
    - wayland
    - wayland-protocols
    - libxkbcommon
    # - ffmpeg
  host:
    - {{ cdt('mesa-libgl') }}
    - {{ cdt('mesa-libegl') }}
    - {{ cdt('libglvnd-glx') }}
    - {{ cdt('libglvnd-egl') }}
    - glew
    # - libpng
    - libjpeg-turbo
    - xorg-libx11
    - zstd
    - wayland
    - libxkbcommon
    - wayland-protocols
    # - ffmpeg

about:
  home: https://github.com/stevenlovegrove/Pangolin
  summary: 'Lightweight portable rapid development library for managing OpenGL.'
  description: |
    Pangolin is a lightweight portable rapid development library for managing OpenGL
    display / interaction and abstracting video input.
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - christian-rauch
